[build]
  publish = "build/"
  command = "npm test && npm run lint && npm run build-prod"

[[redirects]]
  from="/*"
  to="/index.html"
  status=200

[context.branch-deploy.beta]
  API_URL = "https://bracketclub-staging.herokuapp.com"
